### ISSUE TITLE
Run Command On Message Edit

### ISSUE THREAD

**Issue by quiktea** [Gorialis/jishaku#100]
Would it be possible to add a feature where, say you typed a jishaku command wrong and you wanted to edit your message to the correct command., Jishaku would recognise this change and run the command?

**Comment by AbstractUmbra** [comment]
You would typically handle this within your main [`commands.Bot`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#bot) [`on_message_edit`](https://discordpy.readthedocs.io/en/latest/api.html#discord.on_message_edit) event.

A small barebones example is:
```py
@bot.event
async def on_message_edit(before: discord.Message, after: discord.Message) -> None:
  if await bot.is_owner(message.author):
    await bot.process_commands(after)
```

Please note this is barebones and could probably do with more sanity checking, i.e. an edit triggered by embeds and other such items.

**Comment by quiktea** [comment]
Ah, thank you.
