### ISSUE TITLE
Fix jsk shutdown from logout to close.

### ISSUE THREAD

**Issue by JDJGInc** [Gorialis/jishaku#102]
## Checklist

- [ ] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [ ] I have searched the open issues for duplicates
- [ ] I have shown the entire traceback, if possible
- [ ] I have removed my token from display, if visible

**Comment by StarrFox** [comment]
Believe this was already fixed in https://github.com/Gorialis/jishaku/commit/aea7732f3470ac7d41e8824f8441eb82507e5cf5

**Comment by JDJGInc** [comment]
jsk hasn't been pip updated yet

**Comment by ioistired** [comment]
It's not a big deal. logout() has only been deprecated. As long as jishaku pushes to PyPI before dpy 2.0 is released, `jsk shutdown` will continue to work.

**Comment by Gorialis** [comment]
I won't push versions I'm not confident with to PyPI. At the moment, Jishaku 2.0 is pretty different in its command construction from 1.0, so I want it to have gone through more testing (particularly by people who want to subclass Jishaku) before I publish it. I should probably make a milestone for this, but we'll see if that happens.
