### ISSUE TITLE
I am unable to access anything from jishaku

### ISSUE THREAD

**Issue by lazarus-eix** [Gorialis/jishaku#105]
## Summary

I am unable to access anything through load_extension
## Checklist

- [ x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x ] I have searched the open issues for duplicates
- [ ] I have shown the entire traceback, if possible
- [ ] I have removed my token from display, if visible

**Comment by Gorialis** [comment]
This doesn't have enough info to be actionable.
