### ISSUE TITLE
Disable message object to send after execution

### ISSUE THREAD

**Issue by ironman9356** [Gorialis/jishaku#106]
Hey is there a way to disable the message object to be sent after using the ```<prefix>jsk py  await _ctx.send("hello world")```

If not via code then any changes in the source code 

Help appreciated

Thanks in advance

**Comment by ioistired** [comment]
Either do `jsk py "hello world"` or `jsk py py await _ctx.send("hello world") and None`

**Comment by ironman9356** [comment]
Cool thanks for your help
