### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by itPaky** [Gorialis/jishaku#108]
How to install?

i'm so bad

**Comment by JDJGInc** [comment]
either pip install jishaku
pip install git+<github link>
if you use poetry add git+https://github.com/Gorialis/jishaku or poetry add jishaku
if requirements.txt just do jishaku or git+https://github.com/Gorialis/jishaku
it's easy to install.

**Comment by Gorialis** [comment]
This is the first thing the README describes.
