### ISSUE TITLE
Why does Jsk refuse to stay hidden?

### ISSUE THREAD

**Issue by Motzumoto** [Gorialis/jishaku#109]
## Summary

JSK refuses to stay hidden

## Reproduction steps

Theres nothing to replicate, i put 
```py
os.environ.setdefault("JISHAKU_HIDE", "1")
```` 
into my main file and it just doesnt do anything, im importing OS so it should work, but it just doesnt

## Expected results

I expect jsk to be hidden when i boot my bot, normal people shouldnt be able to see it in my help command but i have to keep hiding it after every reboot 

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

Discord Python Version: 1.7.3 Jishaku Version: 2.0.0

- Python v3.8.8-final
--
4 | - discord.py v1.7.3-final
5 | - aiohttp v3.7.4.post0
6 | - system info: Linux 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021

Name: jishaku
--
4 | Version: 2.0.0
5 | Summary: A discord.py extension including useful tools for bot development and debugging.
6 | Home-page: https://github.com/Gorialis/jishaku
7 | Author: Devon (Gorialis) R
8 | Author-email: None
9 | License: MIT
10 | Location: /home/container/.local/lib/python3.8/site-packages
11 | Requires: discord.py, braceexpand, import-expression, humanize
12 | Required-by:

**Comment by JelNiSlaw** [comment]
Does your help command show hidden commands?

**Comment by Motzumoto** [comment]
Alright after tons of tinkering, I finally figured it out

You need to put this in your main file:
```py

@bot.event
async def on_ready():
    bot.load_extension("jishaku")
    print("Loaded JSK")

os.environ.setdefault("JISHAKU_HIDE", "1")
```

**Comment by ioistired** [comment]
@Motzumoto the preferred way to set JISHAKU_HIDE is through environment variables. You do so through your operating system when running your bot. For example, with systemd, you can put an `Environment=JISHAKU_HIDE=1` line under `[Service]`. Or while running from the command line you can do `env JISHAKU_HIDE=1 python bot.py` for example.

**Comment by Motzumoto** [comment]
> @Motzumoto the preferred way to set JISHAKU_HIDE is through environment variables. You do so through your operating system when running your bot. For example, with systemd, you can put an `Environment=JISHAKU_HIDE=1` line under `[Service]`. Or while running from the command line you can do `env JISHAKU_HIDE=1 python bot.py` for example.

Look at my closing reply

**Comment by ioistired** [comment]
Yes, I saw it. That's why I said the *preferred* way.

**Comment by Motzumoto** [comment]
> Yes, I saw it. That's why I said the _preferred_ way.

Ohh, My bad. Thank you
