### ISSUE TITLE
Can't "jsk su" commands in groups

### ISSUE THREAD

**Issue by Makonede** [Gorialis/jishaku#113]
## Summary

Commands inside groups can't be forced to be used by other users via `jsk su`.

## Reproduction steps

* Create a group, and at least one command inside it.
* Attempt to use `jsk su` to force another user to use said command. The group itself works, but `jsk su subcommand`, `jsk su "group subcommand"`, and `jsk su group subcommand` all do not work.

## Expected results

At least one of the methods described above (preferably the former) should allow me to force another user to use said command.

## Actual results

There is absolutely no method to force users to use a subcommand of a group using `jsk su`.

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

* Python v3.9.5-final
* GCC 9.3.0
* discord.py v1.7.3-final
* aiohttp v3.7.4.post0
* Linux 4.4.0-1093-aws
* Jishaku 2.0.0a315+g010991f.master

**Comment by Gorialis** [comment]
I cannot replicate this.
![image](https://user-images.githubusercontent.com/8049998/124295044-56ed4d80-db93-11eb-97d4-f42dcdbf51a2.png)

**Comment by Makonede** [comment]
I tried that, the bot complains it's invalid syntax

**Comment by Gorialis** [comment]
I can only assume, given that I have no other data to go off, that the "invalid syntax" error is coming from whatever command you're invoking and not `jsk su` (given that it is not really possible for it to create a syntax error). `jsk su` only redirects where a command comes from, it cannot make the command itself valid.

**Comment by Makonede** [comment]
You are correct, thanks!
