### ISSUE TITLE
jsk su isn't working at all

### ISSUE THREAD

**Issue by Makonede** [Gorialis/jishaku#118]
## Summary

Attempting to run `jsk su` doesn't do anything at all. All other jishaku commands work fine, but `jsk su` seems to be treated as if it wasn't even a command in the first place. This only started happening in the recent versions of jishaku.

## Reproduction steps

- Attempt to use `jsk su` in any way at all
- Observe

## Expected results

The command works as expected.

## Actual results

It acts as if `jsk su` isn't even a command in the first place.

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

- Python v3.9.6-final
- GCC 9.3.0
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- Linux 4.4.0-1094-aws
- jishaku 2.2.0a341+g673b152.master

**Comment by Gorialis** [comment]
`jsk su` and the other redirection commands were replaced with a different command that is capable of compositing their effects, as written in the [documentation](https://jishaku.readthedocs.io/en/latest/whatsnew.html#version-2-2-0).

**Comment by Makonede** [comment]
Thank you!
