### ISSUE TITLE
KeyError while trying to override jsk

### ISSUE THREAD

**Issue by Soheab** [Gorialis/jishaku#124]
## Summary

I'm trying to override the main jsk command to change the output a little but after trying to load it suddenly raised a key error.

## Reproduction steps

I used the 3rd example shown [here](https://jishaku.readthedocs.io/en/latest/cog.html#adding-or-changing-commands) but with adding the bot my bot via `bot.add_cog`, here is my code:

**file.py:**
```py
class CustomJishaku(*OPTIONAL_FEATURES, *STANDARD_FEATURES):
    @Feature.Command(name = "jishaku", aliases = ["jsk"], invoke_without_command = True, ignore_extra = False)
    async def jsk(self, ctx: commands.Context):
        await ctx.send("I'm walking on a Star!")
        
def setup(bot):
    bot.add_cog(CustomJishaku(bot))
```

**main.py:**
```py
bot.load_extension("folder.file")
```
## Expected results

Excepted it to work fine.

## Actual results

a `KeyError` got raised while trying to load the extension:

```py
Traceback (most recent call last):
  File "...\lib\site-packages\discord\ext\commands\bot.py", line 639, in _load_from_module_spec
    setup(self)
  File "...\folder/file.py", line 460, in setup
    bot.add_cog(CustomJishaku(bot))
  File "...\lib\site-packages\jishaku\features\python.py", line 34, in __init__
    super().__init__(*args, **kwargs)
  File "...\lib\site-packages\jishaku\features\root_command.py", line 52, in __init__
    super().__init__(*args, **kwargs)
  File "...\lib\site-packages\jishaku\features\baseclass.py", line 60, in __init__
    self.bot: commands.Bot = kwargs.pop('bot')
KeyError: 'bot'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 85, in __init__
    self.load_extension(ext)
  File "...\lib\site-packages\discord\ext\commands\bot.py", line 699, in load_extension
    self._load_from_module_spec(spec, name)
  File "...\lib\site-packages\discord\ext\commands\bot.py", line 644, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'folder.file' raised an error: KeyError: 'bot'
```

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

- Python v3.9.6-final
- discord.py: v2.0.0a3453+g58ca9e99
- jishaku: 2.2.0a343+gd1d6485.master
- system info: Windows 10 10.0.22000 (actually i'm on win11)

**Comment by Gorialis** [comment]
This is perhaps a case of confusing (but not incorrect) documentation. As demonstrated (but not explicitly said) [earlier in the section](https://jishaku.readthedocs.io/en/latest/cog.html#custom-cogs-and-the-feature-framework), the Jishaku class only takes `bot` as a keyword, so subclasses must also do so unless they override init: `bot.add_cog(CustomJishaku(bot=bot))`

**Comment by Soheab** [comment]
> This is perhaps a case of confusing (but not incorrect) documentation. As demonstrated (but not explicitly said) [earlier in the section](https://jishaku.readthedocs.io/en/latest/cog.html#custom-cogs-and-the-feature-framework), the Jishaku class only takes `bot` as a keyword, so subclasses must also do so unless they override init: `bot.add_cog(CustomJishaku(bot=bot))`

**Comment by Soheab** [comment]
> This is perhaps a case of confusing (but not incorrect) documentation. As demonstrated (but not explicitly said) [earlier in the section](https://jishaku.readthedocs.io/en/latest/cog.html#custom-cogs-and-the-feature-framework), the Jishaku class only takes `bot` as a keyword, so subclasses must also do so unless they override init: `bot.add_cog(CustomJishaku(bot=bot))`

Ah! My bad, I got linked directly to that part of the docs and didn't bother reading from the start, sorry.

Thank you!
