### ISSUE TITLE
I can't use jishaku.

### ISSUE THREAD

**Issue by Nyan9-Nyan9** [Gorialis/jishaku#133]
Error : 
**Traceback (most recent call last):
  File "/Users/Nyang/Desktop/Code/Main.py", line 7, in <module>
    bot.load_extension('jishaku')
  File "/Users/Nyang/Library/Python/3.8/lib/python/site-packages/discord/ext/commands/bot.py", line 730, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'jishaku' could not be loaded.**

Code:
`
import discord, asyncio, os
from discord.ext import commands

game = discord.Game("접두사 n!")
bot = commands.Bot(command_prefix='n!', status=discord.Status.online, activity=game)

bot.load_extension('jishaku')

@bot.command(aliases=['안녕', 'hi', '안녕하세요','안냥'])
async def hello(ctx):
    await ctx.send(f'{ctx.author.mention}안냥!')

@bot.command(aliases=['맨션', '@'])
async def me(ctx):
    await ctx.send(f'{ctx.author.mention}')

@bot.command(aliases=[' <@!900178789978472449> ', 'Nyang'])
async def re(ctx):
    await ctx.send(f'{ctx.author.mention}{ctx.author.mention}{ctx.author.mention}{ctx.author.mention}')

bot.run('Token')
`

dpy : 1.7.3
jishaku : Last Version

**Comment by Gorialis** [comment]
This implies jishaku isn't available in the same Python environment as your discord.py install. Please check to make sure you're installing both libraries to the same place, else it won't work.
