### ISSUE TITLE
add a flag to force dm traceback

### ISSUE THREAD

**Issue by mysistersbrother** [Gorialis/jishaku#148]
## The Problem

I want all of the exceptions caused by using jishaku eval to be sent directly to my DMS. Currently most flags ARE sent to DMS but some are not. 
```py
if isinstance(exc_val, (SyntaxError, asyncio.TimeoutError, subprocess.TimeoutExpired)):
            # short traceback, send to channel
            await send_traceback(self.message.channel, 0, exc_type, exc_val, exc_tb)
 ```
 I would like a flag to be added that forces any exception to be sent to DMs. Thank you.

**Comment by Gorialis** [comment]
Added `ALWAYS_DM_TRACEBACK` in 1821ded and will be in the next release.
