### ISSUE TITLE
Make BotBase.add_cog() async

### ISSUE THREAD

**Issue by Iinksafe** [Gorialis/jishaku#155]
## Summary

[BREAKING CHANGES] Discord.py has changed some features to async. Therefore, Jishaku won't load since it's using the sync `BotBase.add_cog(Jishaku(bot=bot))` and should now use `await BotBase.add_cog(Jishaku(bot=bot))`.

## Reproduction steps

1. Prepare your Discord.py bot
2. Try to load Jishaku using `await bot.load_extension('jishaku')`.

## Expected results

Jishaku has been added to the bot's cogs / extensions.

## Actual results

Raises an error: 
```
Traceback (most recent call last):
  File "/discord/ext/commands/bot.py", line 803, in _load_from_module_spec
    await setup(self)
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/discord/client.py", line 361, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 1055, in on_ready
    await bot.load_extension("jishaku")
  File "/discord/ext/commands/bot.py", line 869, in load_extension
    await self._load_from_module_spec(spec, name)
  File "/discord/ext/commands/bot.py", line 808, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'jishaku' raised an error: TypeError: object NoneType can't be used in 'await' expression
```

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

### Jishaku
Name: jishaku
Version: 2.3.2
Summary: A discord.py extension including useful tools for bot development and debugging.
Home-page: https://github.com/Gorialis/jishaku
Author: Devon (Gorialis) R
Author-email: None
License: MIT
Location: /opt/virtualenvs/python3/lib/python3.8/site-packages
Requires: click, braceexpand, import-expression
Required-by:

### Discord.py
Name: discord.py
Version: 2.0.0a3882+g934ab415
Summary: A Python wrapper for the Discord API
Home-page: https://github.com/Rapptz/discord.py
Author: Rapptz
Author-email: None
License: MIT
Location: /opt/virtualenvs/python3/lib/python3.8/site-packages
Requires: aiohttp
Required-by: discord

**Comment by Gorialis** [comment]
This was already fixed on master before the PR was even merged. If you're using 2.0a, you can use the development version of Jishaku by following the instructions in the README. I'll work on putting out a release at some other later date.
