### ISSUE TITLE
Remove <Message ...>

### ISSUE THREAD

**Issue by Tommodev-06** [Gorialis/jishaku#165]
How can I remove the second message the bot sent (check the image below)?
![image_2022-04-17_115842989](https://user-images.githubusercontent.com/83727432/163709629-d59abb25-e058-4ba8-843f-d610d3c7188d.png)

**Comment by LostLuma** [comment]
Jishaku automatically returns the result from the last line of your input similarly to the Python REPL, you can avoid it giving any visible output by making it return a `None` result. This can be achieved by putting a `pass` statement or simply `None` on the last line.

**Comment by Gorialis** [comment]
Jishaku by default gives you the direct output of the evaluation you're performing as a shortcut. While you can silence it, in this case it's pretty silly. Just use `len(bot.guilds)` and it will be sent in a message for you.

**Comment by Tommodev-06** [comment]
Thank y'all!
