### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Nziie3** [Gorialis/jishaku#174]
## Summary

An error on startup with jishaku for py-cord 2.0.0b5+. Jishaku tries to use `discord.ui.TextInput` for but the attribute it `discord.ui.InputText` for py-cord.

## Reproduction steps

```py
# with 'client.load_extension('Jishaku')'
python main.py
```

## Expected results

For the client to startup without any errors from Jishaku

## Actual results

I get this error: 
```py
AttributeError: module 'discord.ui' has no attribute 'TextInput'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/main.py", line 17, in <module>
    client.load_extension('jishaku')
  File "/home/container/.local/lib/python3.9/site-packages/discord/cog.py", line 756, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/container/.local/lib/python3.9/site-packages/discord/cog.py", line 687, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'jishaku' raised an error: AttributeError: module 'discord.ui' has no attribute 'TextInput'
```

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

Py-cord: 2.0.0b5
Jishaku: 2.5.0

**Comment by Nziie3** [comment]
**WAS TOLD BY PY-CORD DEVS THAT JISHAKU DOESNT WORK WITH PYCORD ANYMORE :(**

**Comment by Gorialis** [comment]
Fallback created in bc90861d875f9053151abc22c533817ba2db4f98
