### ISSUE TITLE
An option to hide jishaku's cog automatically on bot startup

### ISSUE THREAD

**Issue by timelessnesses** [Gorialis/jishaku#178]
## The Problem

I am making help command and i need to do command `<prefix>jsk hide` everytime I want to hide jsk.  
Can I hide this automatically by setting some property or stuff?

## The Ideal Solution

Maybe something like env variable like
```dotenv
JISHAKU_HIDE_HELP=true
```
or set it in python
```py
jishaku.hide_help = True
```
or maybe config file?
```ini
JISHAKU_HIDE_HELP=true
```

## The Current Solution

I need to always run `<prefix>jsk hide` to hide jishaku from my help menu

## Summary

Add any feature that can hide jishaku's help inside bot's code or on_ready function or something

**Comment by Gorialis** [comment]
This already exists, you set `JISHAKU_HIDE=1` in your env.
