### ISSUE TITLE
Whenever I run my JSK custom command, I get "Too many arguments passed into jishaku."

### ISSUE THREAD

**Issue by JayKash357** [Gorialis/jishaku#181]
## Reproduction steps

The condition that the bug occurs is in the title. Code:
import discord
import logging
from discord.ext import commands
from jishaku.features.baseclass import Feature
from jishaku.cog import STANDARD_FEATURES, OPTIONAL_FEATURES

class CustomDebugCog(*OPTIONAL_FEATURES, *STANDARD_FEATURES):
	@Feature.Command(parent="jsk", name="execute_sql")
	async def jsk_execute_sql(self, ctx: commands.Context):
		await ctx.send("test")
		#try:
			#await self.execute_sql(query)
		#except Exception as e:
			#await ctx.send("Error (printed to console)")
			#logging.error(e)

def setup(bot: commands.Bot):
	bot.add_cog(CustomDebugCog(bot=bot))
		

## Expected results

I expected it to actually run the command and send test in the channel it's run in.

## Actual results

Command didn't run. Traceback:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1330, in invoke
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1619, in invoke
    await super().invoke(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 987, in invoke
    await self.prepare(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 904, in prepare
    await self._parse_arguments(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 832, in _parse_arguments
    raise TooManyArguments('Too many arguments passed to ' + self.qualified_name)
discord.ext.commands.errors.TooManyArguments: Too many arguments passed to jishaku

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

 

Jishaku 2.50, discord.py 2.0.0a

**Comment by pythonmcpi** [comment]
The issue here is that you never loaded the extension that your CustomDebugCog is in. You're probably loading default jishaku instead. Find the line that reads `await bot.load_extension("jishaku")` and change `"jishaku"` to the file you placed the CustomDebugCog code in.

Also, your code fails with an error when loaded as an extension because your `setup` function must be a coroutine. (This has been the case since discord.py 2.0.) You will also need to `await` the `bot.add_cog` call.

**Comment by JayKash357** [comment]
Thank you, but I kinda quit Python and just stuck with C# and C++ stuff.😅

**Comment by Gorialis** [comment]
Seems like this is resolved and not an internal issue - closing
