### ISSUE TITLE
Changing jsk command permissions

### ISSUE THREAD

**Issue by Nzii3** [Gorialis/jishaku#182]
Is it possible to change the permissions of jishaku commands? I have multiple people who contribute to the bot and are trusted and I was wondering if it’s possible to pass other owner_ids only with jishaku?

**Comment by AbstractUmbra** [comment]
This is automatically done if the Bot application is registered to a Team within the api. You can do this from the [develop portal](https://discordapp.com/developers/applications).

If you would like to do this programmatically instead, you must change `Bot.owner_id` to `None` and then set `Bot.owner_ids` to a Sequence of IDs, like a `list`, `tuple` or `set`.

**Comment by Nzii3** [comment]
Oh ok, thanks.
