### ISSUE TITLE
Add Whois command

### ISSUE THREAD

**Issue by tuna2134** [Gorialis/jishaku#194]
## Add Whois command

I want to get domain information.

## The Ideal Solution

Make command like `jsk pip`

## Summary

And run whois with subprocess.

**Comment by Gorialis** [comment]
My main concern with this is having to build in dependence to a whole bunch of web servers to implement it properly. Compared to e.g. just pulling DNS records, where I can rely on your system config, to get WHOIS info I need to figure out which of a [list of a lot of possible servers](https://github.com/richardpenman/whois/blob/07aaee6c9b5c9850579675e07d2eacf5214e0796/whois/whois.py#L50-L113) actually has the info I need, and this list can change over time and ever expands with more TLDs.

Having to maintain that within jishaku seems obviously quite tedious and silly, so it would call for pulling in a dependency that can separately ensure it is up to date, but that requires picking one that is actively maintained/has async support/doesn't pull in too many dependencies of its own/etc. It's not a no (I thought about adding DNS lookup before, and that would probably go in with this if it does end up happening someday), but it leans into the dubious region of "is jishaku a tool people should use for this" chart.

**Comment by tuna2134** [comment]
I see
