### ISSUE TITLE
change jishaku commands names 

### ISSUE THREAD

**Issue by Noraa08** [Gorialis/jishaku#201]
Can the commands be renamed to jishaku? So instead of being `!jsk py` it is `!uni py` or `!uni e`

**Comment by Gorialis** [comment]
Yes - the documentation doesn't cover this specifically but if you follow the bit on [replacing the base command](https://jishaku.readthedocs.io/en/latest/cog.html#adding-or-changing-commands), you can rename the root command using the decorator so long as the function name remains `jsk`.
