### ISSUE TITLE
Cog already loaded when loading it

### ISSUE THREAD

**Issue by Kellyaka** [Gorialis/jishaku#208]
## Summary

When i was tryin to load/Reload a Cog it says its alreaedy loaded but when i tried to unload it it said its not loaded but when i try again loading same errro
## Reproduction steps

idk honestly

## Expected results
i expected for the Cog to load/reload when i tried loading/reloadin and unload when i try to unload

## Actual results

i explained it in sumery

## Checklist

- [yes] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [yes] I have searched the open issues for duplicates
- [yes] I have shown the entire traceback, if possible
- [yes] I have removed my token from display, if visible

## System information

![image](https://github.com/Gorialis/jishaku/assets/72246241/e5b46860-29dd-43ab-ba0f-4264a744359d)

**Comment by Gorialis** [comment]
The error describes exactly what it takes issue with - there is a cog called `LevelingSystem` already loaded somewhere in your bot. It does **not** have to be part of the same extension/file - you likely have two cogs named the same thing in different files, which discord.py does not allow.

You can figure out where your culprit resides by doing `jsk py _bot.cogs['LevelingSystem'].__module__`.
