### ISSUE TITLE
I can’t use jishaku shell command

### ISSUE THREAD

**Issue by tuna2134** [Gorialis/jishaku#209]
## Summary

I can’t use jishaku shell command

## Reproduction steps

Use docker image("python:3-alpine”)

## Expected results

Run command

## Actual results

```py

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/jishaku/features/shell.py", line 87, in jsk_shell
    with ShellReader(argument.content, escape_ansi=not Flags.use_ansi(ctx)) as reader:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jishaku/shell.py", line 86, in __init__
    self.process = subprocess.Popen(sequence, stdout=subprocess.PIPE, stderr=subprocess.PIPE)  # pylint: disable=consider-using-with
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/bin/bash'
```

## Checklist

- [ ] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [ ] I have searched the open issues for duplicates
- [ ] I have shown the entire traceback, if possible
- [ ] I have removed my token from display, if visible

## System information

- discord.py v2.3.2
- jishaku v2.5.1

**Comment by Gorialis** [comment]
While this falls into a weird documentation hole (I really need to get this consistent eventually), the [README](https://github.com/Gorialis/jishaku#-jishaku-shshell-argument) mentions that the shell command looks at your `SHELL` environment variable or otherwise uses `/bin/bash`. So to fix this, you either need to set `SHELL` to a suitable shell (such as `/bin/sh`), or install bash.

**Comment by tuna2134** [comment]
I see thanks
