### ISSUE TITLE
PaginatorInterface stops being interactive when message leaves the cache

### ISSUE THREAD

**Issue by SnowyLuma** [Gorialis/jishaku#31]
Using jishaku on a bot which has a smaller than default message cache or receives a lot of messages currently causes paginators to stop being interactive before the one hour timeout.

It would be useful if instead of relying on messages being in the cache raw events were used, as this behavior is pretty irritating when trying to debug.

**Comment by Gorialis** [comment]
Should be fixed by 0f2f20ff8a673d0576f774edd2094f67414a0b2f. Reopen if you notice any problems.
