### ISSUE TITLE
Add `update` command to Jishaku

### ISSUE THREAD

**Issue by rainbowCultist** [Gorialis/jishaku#32]
Currently, you can run a few commands to update Jishaku on the bot remotely through Discord, and this would be a cool thing to be able to do with one simple `update` command.

**Comment by Gorialis** [comment]
Unlikely to be practically implementable.

**Comment by Gorialis** [comment]
Following a large amount of design speculation and reflection on implementation approaches I have concluded that there is no sensible, acceptable way to implement this reliably, securely and agnosticly. As such, I'm going to make no further attempt to implement this myself.

PRs are still welcome on this topic, but I doubt this will ever be a thing.
