### ISSUE TITLE
Add _get and _find helpers

### ISSUE THREAD

**Issue by slice** [Gorialis/jishaku#35]
This isn't a pull request because the implementation is quite trivial, but I propose that `_get` and `_find` should be added to the injected locals of jishaku's repl. These will obviously correlate to `discord.utils.get` and `discord.utils.find`.

I propose this change because these two functions are quite commonly used throughout code that uses Discord.py, both in cog code and in repl code.

## Statistics

Searching for "jsk py discord.utils.get" in the Discord.py server returns 98 results, so we know that this function is used commonly in the jishaku repl. "jsk py discord.utils.find" returns 14 results.

While the latter result is not as common, I believe that it should be included alongside `get` as they seem to work in conjunction in performing a similar task (fetching something from an iterable due to arbitrary criteria).

Length-wise, these aliases would also save on typing. For example, `_author` is aliased to `_ctx.author`. That saves about 4 characters of typing. However, the `_get` alias would save 13 characters of typing total, which is a larger benefit. Alongside being a larger benefit, this function is used all over the place (see aforementioned points), so I believe that it would be worth it to include.

## Naming

I don't think that the `_get` and `_find` names can be easily mistaken for something else, or that conflicts will be introduced. There is already the `_` prefix, and even moderately experienced Discord.py developers are able to infer what the function aliases to due to their ubiquitous usage in various codebases.

**Comment by Gorialis** [comment]
Added as of 1.12.0 (5b70437803bb2ae0f4b35a7680880d7e26aed745)
