### ISSUE TITLE
Is it possible to make jishaku hide by default.

### ISSUE THREAD

**Issue by 12944qwerty** [Gorialis/jishaku#37]

**Comment by SnowyLuma** [comment]
You can set the `JISHAKU_HIDE` environment variable to a bool-like string to achieve this, the possible values are `true`, `t`, `yes`, `y`, `on` and `1`.

See #4 and the closing commit ca5fa0bdf5a40e7e764050ca7f5234791446b3d1 for the implementation / discussion.

**Comment by 12944qwerty** [comment]
I'm confused..... How would I change the JISHAKU_HIDE var? would I have to make my own .env with it?

**Comment by bmintz** [comment]
It depends on the OS and process manager you use. How are you running your bot? Are you using systemd, init scripts, Windows service manager, running your bot directly on the command line, launchd, or something else?

**Comment by 12944qwerty** [comment]
Oh. I forgot about this. I got it to work :) (I use repl) (which does suck)
