### ISSUE TITLE
print and others don't work

### ISSUE THREAD

**Issue by MinerChAI** [Gorialis/jishaku#38]
When I do `$jsk py print('Hello, world!')` it doesn't give me anything. Just check this: 
![image](https://user-images.githubusercontent.com/43097806/56689976-04779300-66e5-11e9-838f-84f028692113.png)
[Here's eval.py cog](https://gist.github.com/MinerChAI/00c0c2211218cb6096e713cf230a3285#file-eval-py)

**Comment by bmintz** [comment]
The standard output and standard error of your code is deliberately not captured. Doing so (as you have done on line 67) can interfere with printing in other parts of your bot.

Jishaku provides an alternate way of sending intermediate results. Try using `yield "Hello, world!"` instead.

**Comment by Gorialis** [comment]
See #39 as to why this is not allowed. You can use `yield`, `return` or `await _ctx.send(...)` instead to send values back to chat. A `print` shim might exist in the future, but it is unlikely due to sync/async difficulties.
