### ISSUE TITLE
pip install jishaku requires a non existing version of discord 

### ISSUE THREAD

**Issue by stefanfx** [Gorialis/jishaku#50]
### Summary

When running pip install jishaku i get following error:
`Collecting discord.py>=1.3.0a2084 (from jishaku)
  Could not find a version that satisfies the requirement discord.py>=1.3.0a2084 (from jishaku) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.8, 0.16.9, 0.16.10, 0.16.11, 0.16.12, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3)
No matching distribution found for discord.py>=1.3.0a2084 (from jishaku)`

### Reproduction steps

run pip install jishaku in command prompt 
### Expected results

Jishaku installs
### Actual results

Error saying that discord version was not found

### Checklist

- [x ] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x ] I have searched the open issues for duplicates
- [ x] I have shown the entire traceback, if possible
- [ x] I have removed my token from display, if visible

### System information

No jishaku and discord.py 1.3.0a

**Comment by Gorialis** [comment]
My bad, I forgot that I had put the requirements bump on stash. It was supposed to wait until 1.3.0 released.

**Comment by Gorialis** [comment]
v[1.16.1](https://pypi.org/project/jishaku/1.16.1.147/) has been [pushed by CI](https://gitlab.com/Gorialis/jishaku/-/jobs/301831839) so this issue should now be fixed. Rerun the install and see if it fixes it on your machine.

**Comment by stefanfx** [comment]
Fixed
Thanks
