### ISSUE TITLE
Is possible to use jishaku python execute in own command?

### ISSUE THREAD

**Issue by ks129** [Gorialis/jishaku#51]
Is possible to make use Jishaku in my !execute command? This would execute python shell.

**Comment by iomintz** [comment]
Take a look at AsyncCodeExecutor.

https://github.com/Gorialis/jishaku/blob/b3bf5dbb22e370aa9c8341ba9d0efc787ccfa892/jishaku/repl/compilation.py#L102-L157

If you use this in your execute command, you will be missing certain jishaku features, such as auto-conversion of yielded discord.Embed objects. Alternatively you can call `await ctx.invoke(bot.get_command('jsk py'), argument=jishaku.codeblocks.codeblock_converter(your_code_here))`.

**Comment by Gorialis** [comment]
AsyncCodeExecutor isn't very well documented right now, but it's designed to be usable independently of the command (this is both to make it testable and so you can add your own extra functionality).

I recommend taking a look at how `jsk py` is implemented if you want to use the REPL core without using the actual command. This code can be greatly simplified if you don't care about retention, responding to yields or output formatting.
https://github.com/Gorialis/jishaku/blob/d7746ecc093b2472d9efaa403e9e9dfad911b3ff/jishaku/cog_base.py#L474-L521
