### ISSUE TITLE
Local Host .env variable JISHAKU_NO_UNDERSCORE = true doesn't work

### ISSUE THREAD

**Issue by ssebastianoo** [Gorialis/jishaku#59]
### Summary

I am trying to remove the `_` before ctx, author... and if I do it with a host it works, but if I do it in local host it doesn't work.

### Reproduction steps

Create a `.env` file, add `JISHAKU_NO_UNDERSCORE = true` to it, run a thing like `jsk py author.name`

### Expected results

It should work without the underscore

### Actual results

It works only with the underscore

### Checklist

- [ x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x ] I have searched the open issues for duplicates
- [ ] I have shown the entire traceback, if possible
- [ x] I have removed my token from display, if visible

### System information

Jishaku: `Version: 1.18.1.187`
discord.py: `Version: 1.3.2`
Ruuning on `Windows-10-10.0.18362-SP0`

**Comment by skyblockz** [comment]
Did you even load the environment

**Comment by Gorialis** [comment]
Jishaku uses [`os.getenv`](https://github.com/Gorialis/jishaku/blob/d7746ecc093b2472d9efaa403e9e9dfad911b3ff/jishaku/flags.py#L24) which is the Python standard library way of getting the values of environment variables.

The flag not being read means it's not in the environment, which is probably to do with you being on a Windows host that has no compatibility with `.env` files, perhaps unlike your remote host. This is thus not an issue with Jishaku (as setting the flags in a Windows-compatible way, e.g. `$env:JISHAKU_NO_UNDERSCORE=1;` in PowerShell works fine).
