### ISSUE TITLE
Unable to receive messages

### ISSUE THREAD

**Issue by para-dise** [Gorialis/jishaku#64]
### Summary

Jishaku seems to throw an error when attempting to send a msg via multiple commaands:
- jsk help
- jsk cog

### Reproduction steps

Running jsk help

### Expected results

a proper execution of the command

### Actual results

Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/botuser/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 104, in on_command_error
    await channel.send(embed=embed)
AttributeError: 'NoneType' object has no attribute 'send'

### Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

### System information

`Python v3.7.3-final
discord.py v1.3.3-final
aiohttp v3.6.2
websockets v8.1
system info: Linux 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)`

`
Name: jishaku
Version: 1.18.2.190
Summary: A discord.py extension including useful tools for bot development and debugging.
Home-page: https://github.com/Gorialis/jishaku
Author: Devon (Gorialis) R
Author-email: None
License: MIT
Location: /home/botuser/.local/lib/python3.7/site-packages
Requires: import-expression, discord.py, braceexpand, humanize
Required-by: `

**Comment by StarrFox** [comment]
This seems to be an issue with your on_command_error event, since jsk doesn't have a help or cog subcommand it's raising discord.ext.commands.TooManyArguments.
You probably meant to do "help jsk".

**Comment by para-dise** [comment]
> This seems to be an issue with your on_command_error event, since jsk doesn't have a help or cog subcommand it's raising discord.ext.commands.TooManyArguments.
> You probably meant to do "help jsk".

My brain must be failing my I would've swore there was jsk help and jsk cog unload/reload before... oh well tx

**Comment by iomintz** [comment]
There are *extension* reload facilities. Try jsk unload/reload/load.
