### ISSUE TITLE
`jsk py False` sends nothing back

### ISSUE THREAD

**Issue by bmintz** [Gorialis/jishaku#7]
## Steps to reproduce

1. Send `<prefix>jsk py False` or `<prefix>jsk py _msg.author.bot`

## Expected behavior

False is sent back

## Actual behavior

Nothing is sent back

## Workaround

Use `pywhat` or wrap expressions that evaluate to booleans in a call to `str()`.

**Comment by Gorialis** [comment]
Fixed with [0.1.2](https://github.com/Gorialis/jishaku/releases/tag/0.1.2).
