### ISSUE TITLE
Make it easier to create aliases for commands

### ISSUE THREAD

**Issue by mesub7** [Gorialis/jishaku#74]
### The Problem

 I would love it if you could make it easier to add aliases without overriding commands. I think it would make life easier for quite a few people.

### The Ideal Solution

 Add a command for it (!jsk alias [command] [allias])

### The Current Solution

 Currently you need to make your own cog or edit the source code (which is tedious since you'll have to redo it every time there is an update)

### Summary

 Make it easier to add aliases without overriding commands.

**Comment by iomintz** [comment]
This seems like a rather niche use-case for something that can be easily done with a custom command:
```py
@commands.command()
async def alias(self, ctx, cmdname, alias):
	cmd = ctx.bot.get_command(cmdname)
	cmd.aliases.append(alias)
	# register the modified command
	ctx.bot.remove_command(cmdname)
	ctx.bot.add_command(cmd)
```

**Comment by mesub7** [comment]
Fair enough, thanks!
