### ISSUE TITLE
How do I change emojis of jishaku?

### ISSUE THREAD

**Issue by FrostiiWeeb** [Gorialis/jishaku#84]
I want to change the reactions for jishaku please help.

**Comment by Gorialis** [comment]
Assuming that this refers to `PaginatorInterface` or commands that use it:

If you're using PaginatorInterface yourself, you can create an instance of EmojiSettings to configure your own interfaces:
```py
from jishaku.paginators import EmojiSettings, PaginatorInterface

# These are identical to the defaults, but change them to what you would want to use.
emoji_settings = EmojiSettings(
    start="\N{BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR}",
    back="\N{BLACK LEFT-POINTING TRIANGLE}",
    forward="\N{BLACK RIGHT-POINTING TRIANGLE}",
    end="\N{BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR}",
    close="\N{BLACK SQUARE FOR STOP}"
)

...
interface = PaginatorInterface(bot, paginator, emoji=emoji_settings)
```

As for commands that use it, such as `jsk cat`, there is currently no way to do this.
I have received requests for this feature before, and I want to implement it, but for a time there were discussions about whether discord.py itself would provide some form of interface for configuring cogs following the idea of 'package cogs' (such as jishaku) becoming more of a popular concept. As of yet, there is no such mechanism, and so there is no real way to configure jishaku directly outside of environment variables.

In the future, I may create some awkward filler method of doing this to cover the slack, like maybe `bot.jsk_config = {}`, but bots having things such as e.g. multiple instances of jishaku cogs loaded at once with independent local states is a use case I want to be able to support so I will need to figure out some good way of approaching it.

**Comment by FrostiiWeeb** [comment]
Alright, thanks!
