### ISSUE TITLE
Can't import jishaku.features.*

### ISSUE THREAD

**Issue by NarmyOnDiscord** [Gorialis/jishaku#98]
## Summary

I wanna import Features to write my own jishaku commands, but 

## Reproduction steps

Just completly reinstall jishaku with the normal command
pip install -U jishaku

## Expected results

You're able to import jishaku.features.*

## Actual results

You cant

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible - There isnt one
- [x] I have removed my token from display, if visible

## System information

d.py: 1.6.0
Jishaku: 1.20.0.220

**Comment by NarmyOnDiscord** [comment]
Also I tried the steps in https://github.com/Gorialis/jishaku/issues/81, so idk whats wrong

**Comment by Gorialis** [comment]
Features are part of Jishaku 2.0, which is not released on PyPI yet, as it is still in development. You need to install a development version as advised in the README if you want to use 2.0.
