### ISSUE TITLE
How do I add users to Jishaku?

### ISSUE THREAD

**Issue by TheUndeadBowman** [Gorialis/jishaku#99]
I want my friend to be able to use Jishaku commands, but currently only I am able to do so. How do I add him?

**Comment by SnowyLuma** [comment]
Jishaku internally uses the [`is_owner`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Bot.is_owner) method on your bot instance to check whether a user can execute commands.

You can overwrite bot owners by passing the `owner_ids` attribute when constructing the bot, overwriting the method itself to add custom logic, or adding someone to the developer team the bot is in (if your bot is not in a team you can create one [in the developer portal](https://discord.com/developers/teams) and transfer your bot to it).

**Comment by Gorialis** [comment]
The appropriate means of doing this is described in the documentation under the [Changing who can use Jishaku](https://jishaku.readthedocs.io/en/latest/cog.html#changing-who-can-use-jishaku) section.
